# Generated by Django 5.2 on 2025-08-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('category', models.CharField()),
                ('description', models.TextField()),
                ('image', models.CharField()),
            ],
        ),
    ]
