# Generated by Django 5.2 on 2025-08-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField()),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField()),
                ('address2', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zipcode', models.CharField()),
            ],
        ),
    ]
